# Test Version

special_tokens:
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '<pad>'
    mask_token: '<mask>'
    sep_token: '<sep>'

additional_tokens:
    gen_token: '<gen>'
    blk_token: '<blk>'
    none_token: '<none>'
    mask_gen_task_token: '<maskgenTask>'
    mask_gen_task_token_for_dec: '<maskgenTask_d>'
    gen_task_token: '<genTask>'
    gen_task_token_for_dec: '<genTask_d>'
    con_task_token: '<conTask>'
    con_task_token_for_s: '<conTask_s>'
    con_task_token_for_ro: '<conTask_ro>'
    den_task_token: '<denTask>'
    den_task_token_for_dec: '<denTask_d>'
    rec_task_token: '<recTask>'
    rec_task_token_for_dec: '<recTask_d>'
    cla_task_token: '<claTask>'

relation_tokens:
    - '<AtLocation>'
    - '<CapableOf>'
    - '<Causes>'
    - '<CausesDesire>'
    - '<CreatedBy>'
    - '<DefinedAs>'
    - '<DesireOf>'
    - '<Desires>'
    - '<HasA>'
    - '<HasFirstSubevent>'
    - '<HasLastSubevent>'
    - '<HasPainCharacter>'
    - '<HasPainIntensity>'
    - '<HasPrerequisite>'
    - '<HasProperty>'
    - '<HasSubEvent>'
    - '<HasSubevent>'
    - '<HinderedBy>'
    - '<InheritsFrom>'
    - '<InstanceOf>'
    - '<IsA>'
    - '<LocatedNear>'
    - '<LocationOfAction>'
    - '<MadeOf>'
    - '<MadeUpOf>'
    - '<MotivatedByGoal>'
    - '<NotCapableOf>'
    - '<NotDesires>'
    - '<NotHasA>'
    - '<NotHasProperty>'
    - '<NotIsA>'
    - '<NotMadeOf>'
    - '<ObjectUse>'
    - '<PartOf>'
    - '<ReceivesAction>'
    - '<RelatedTo>'
    - '<SymbolOf>'
    - '<UsedFor>'
    - '<isAfter>'
    - '<isBefore>'
    - '<isFilledBy>'
    - '<oEffect>'
    - '<oReact>'
    - '<oWant>'
    - '<xAttr>'
    - '<xEffect>'
    - '<xIntent>'
    - '<xNeed>'
    - '<xReact>'
    - '<xReason>'
    - '<xWant>'
