name: 'atomic'
truncate:
    subj_len: 25
    obj_len: 25
dir:
    train: '/mnt/data/user8/solar-commonsense_inference/data/tuple_data/atomic/train.tsv'
    dev: '/mnt/data/user8/solar-commonsense_inference/data/tuple_data/atomic/dev.tsv'
    test: '/mnt/data/user8/solar-commonsense_inference/data/tuple_data/atomic/test.tsv'
sim:
    train: '/mnt/data/user8/solar-commonsense_inference/data/sim_mat/atomic/train_subj_dist__a_concept_related_to.pkl'
    dev: '/mnt/data/user8/solar-commonsense_inference/data/sim_mat/atomic/dev_subj_dist__a_concept_related_to.pkl'
